services:
  redmine-db:
    image: mysql:8.0
    container_name: redmine-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: redmine
      MYSQL_USER: redmine
      MYSQL_PASSWORD: redmine_password
    volumes:
      - redmine_db_data:/var/lib/mysql
    networks:
      - redmine_network
    command: --default-authentication-plugin=mysql_native_password

  redmine:
    image: redmine:5.1
    container_name: redmine-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REDMINE_DB_MYSQL: redmine-db
      REDMINE_DB_USERNAME: redmine
      REDMINE_DB_PASSWORD: redmine_password
      REDMINE_DB_DATABASE: redmine
      REDMINE_SECRET_KEY_BASE: supersecretkey
    volumes:
      - redmine_data:/usr/src/redmine/files
      - redmine_plugins:/usr/src/redmine/plugins
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      - redmine-db
    networks:
      - redmine_network

volumes:
  redmine_db_data:
  redmine_data:
  redmine_plugins:

networks:
  redmine_network:
    driver: bridge